NAME        := webserv

CXX         := c++
CXXFLAGS    := -Wall -Wextra -Werror -std=c++98 -pedantic
CPPFLAGS    := -Iinclude
LDFLAGS     :=

SRC_DIR     := src
OBJ_DIR     := build
INC_DIR     := include

SOURCES     := $(wildcard $(SRC_DIR)/*.cpp)
OBJECTS     := $(SOURCES:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)
# One .d file per translation unit, generated by the compiler itself, so that
# editing a header rebuilds exactly the objects that include it. The original
# Makefile listed objects by hand and tracked no headers at all, which meant a
# header change quietly produced a binary built from stale objects.
DEPENDS     := $(OBJECTS:.o=.d)

.PHONY: all clean fclean re debug sanitize test run

all: $(NAME)

$(NAME): $(OBJECTS)
	@printf '  \033[32mLD\033[0m      %s\n' '$@'
	@$(CXX) $(OBJECTS) $(LDFLAGS) -o $@

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp | $(OBJ_DIR)
	@printf '  \033[36mCXX\033[0m     %s\n' '$<'
	@$(CXX) $(CXXFLAGS) $(CPPFLAGS) -MMD -MP -c $< -o $@

$(OBJ_DIR):
	@mkdir -p $(OBJ_DIR)

# Build with debug symbols and no optimisation, for gdb or lldb.
debug: CXXFLAGS += -g3 -O0 -DDEBUG
debug: re

# AddressSanitizer and UndefinedBehaviorSanitizer. This is the configuration
# that proves the use-after-free and out-of-bounds classes of bug are gone,
# rather than merely not reproducing today.
sanitize: CXXFLAGS += -g3 -O1 -fsanitize=address,undefined -fno-omit-frame-pointer
sanitize: LDFLAGS  += -fsanitize=address,undefined
sanitize: re

test: $(NAME)
	@./tests/run_tests.sh

run: $(NAME)
	@./$(NAME) conf/default.conf

clean:
	@rm -rf $(OBJ_DIR)
	@printf '  \033[33mRM\033[0m      %s\n' '$(OBJ_DIR)'

fclean: clean
	@rm -f $(NAME)
	@printf '  \033[33mRM\033[0m      %s\n' '$(NAME)'

re: fclean all

-include $(DEPENDS)
